# site settings
title: Restaurant de l'Ill
subtitle:
email: restodelill@gmail.com
description: Restaurant gourmand sur les bords de l\'Ill
baseurl:  # the subpath of your site, e.g. /blog
url: http://restaurantdelill.com # the base hostname & protocol for your site
author:
street_address: 14 rue du Général Leclerc
city: Ebermunster
 #state: FR
zip_code: 67600
country: France
phone: 03 88 85 75 40

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/restaurantdelillebersmunster/
github_url:
gitlab_url: # https://gitlab.com/u/andrewbanchich
googleplus_url: #https://plus.google.com/u/0/+AndrewBanchich
instagram_url: #https://instagram.com
linkedin_url: #https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: #https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed


# Restaurant settings

restaurant:
  starter:
    - name: La tartinette
      desc: Chèvre frais fermier, jambon fumé, tomate et sa salade
      prix: 8.5
    - name: Les asperges d'Alsace
      desc: aux deux jambons & mayonnaise maison
      prix: 9.00
    - name: Les escargots douzaine
      desc:
      prix: 14.00
    - name: Les escargots 1/2 douzaine
      desc:
      prix: 7.00
  maindish:
    - name: Les carpes Frites
      desc: Trois sauce, salade et frites
      prix: 19.00
    - name: Le carré de veau grillé
      desc: Sauce crème & champignons, frites et lgumes du moment
      prix: 21.00
    - name: Le filet de sandre
      desc: Sauce a la crème, nouilles et légumes du moment
      prix: 20.5
    - name: L'entrecôte (qualité supérieur)
      desc: Sauce au poivre vert, frites et salade
      prix: 23.00
  dessert:
    - name: l'Assiette de fromages
      desc: assortiment de fromages et sa salade
      prix: 5.50
    - name: L'ananas flambé
      desc: 1/2 ananas flambé au rhum et sa note vanilléé
      prix: 7.50
    - name: Irish Coffee
      desc: Whisky,sucre de canne, espresso et chantilly
      prix: 7.00

